config/routes.rb
Rails.application.routes.draw do
  get '/', to: "application#home", as: "home"
  resources :rentals
  resources :videogames
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :user
    belongs_to :videogame

    def start_date_format
        self.start_date.strftime("%m/%d/%Y")
    end

    def end_date_format
        self.end_date.strftime("%m/%d/%Y")
    end

    def calculate_days 
       start = self.start_date
       end_date = self.end_date

       diff = (end_date - start)

       (diff/1.day).round  
    end

    def rental_price
        rental_amount = calculate_days * 2
        self.price = rental_amount
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :rentals , dependent: :destroy
    has_many :videogames, through: :rentals
    accepts_nested_attributes_for :videogames


end

app/models/videogame.rb
class Videogame < ApplicationRecord
    has_many :rentals, dependent: :destroy
    has_many :users, through: :rentals

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :find_rental, only: [:show, :update, :edit]

    def index
        @rentals = Rental.all
    end

    def show
    end

    def new
        @rental = Rental.new
    end

    def create
        @rental = Rental.create(rental_params)

        redirect_to rental_path(@rental)
    end

    def edit
    end
    
    def update
    end

    private

    def rental_params
        params.require(:rental).permit(:start_date, :end_date, 
        :videogame_id, :user_id)
    end

    def find_rental
        @rental = Rental.find(params[:id])
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @users = User.all
end

def show
    @user = User.find(params[:id])
end

def new
    @user = User.new
    @user.videogames.build
end

def create
    user = User.create(user_params)
    redirect_to user_path(user)
end

def edit
    @user = User.find(params[:id])
end

def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
end

private
def user_params
    params.require(:user).permit(:name, :age, 
    videogames_attributes: [
        :title,
        :erb_rating
    ])
end

end

app/controllers/videogames_controller.rb
class VideogamesController < ApplicationController
    before_action :find_videogame, only: [:show, :update, :edit, :destroy]

    def index
        @videogames = Videogame.all
    end

    def show
    end

    def new
        @videogame = Videogame.new
    end

    def create
        @videogame = Videogame.create(game_params)

        redirect_to videogame_path(@videogame)
    end

    def edit
    end

    def update
        @videogame.update(game_params)
        
        redirect_to videogame_path(@videogame)
    end

    def destroy
        @videogame.destroy

        redirect_to videogames_path
    end
    
    private
    def game_params
        params.require(:videogame).permit(:title, :erb_rating)
    end

    def find_videogame
        @videogame = Videogame.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/application/home.html.erb
<h1>Welcome to Video Game Rentals</h1>

<h2>Show All Users Or Create New User</h2>
<button><%= link_to "New User", new_user_path %> </button>
<button><%= link_to "Show Users", users_path %></button>


<h2>Show All Rentals 0r Create New Rental</h2>
<button><%= link_to "New Rental", new_rental_path %></button>
<button><%= link_to "Show Rentals", rentals_path %></button>


<h2>Show All Video Games or Create New Video Game</h2>
<button><%= link_to "New Video Game", new_videogame_path %></button>
<button><%= link_to "Show All Video Games", videogames_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameRentals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_for @rental do |f| %>
<%= f.label :start_date %> 
<%= f.date_field :start_date %> <br><br>
<%= f.label :end_date %>
<%= f.date_field :end_date %>

<br><br>
<label for="videogame">Video Game: </label> 
<%= f.collection_select :videogame_id, Videogame.all, :id, :title %>
<br> <br>
<label for="User">Select User:</label>
<%= f.collection_select :user_id, User.all, :id, :name %>
<br> <br>
<%= f.submit "Create Rental" %>
<%end %>

app/views/rentals/edit.html.erb
<h1>Edit Rental</h1>

<%= render 'form' %>

app/views/rentals/index.html.erb
<h1>All Rentals</h1>

<% @rentals.each do |rentals| %>
    <h2>
        <%= link_to "#{rentals.user.name} - #{rentals.videogame.title}", rental_path(rentals) %> - <%= rentals.start_date_format %>
    </h2>
<% end %>

<button><%= link_to "Return Home", home_path %></button>

app/views/rentals/new.html.erb
<h1>Enter New Rental</h1>

<%= render 'form' %>

app/views/rentals/show.html.erb
<h1>Rental Details</h1>

<h2><%= link_to @rental.user.name, user_path(@rental.user) %></h2>
<h2><%= link_to @rental.videogame.title, videogame_path(@rental.videogame) %></h2>
<h3>Start Date: <%= @rental.start_date_format %></h3>
<h3>End Date: <%= @rental.end_date_format %></h3>
<h4>Rental Duration : <%= @rental.calculate_days %> Days</h4>


<% if @rental.rental_price > 0 %>
    <h4>Rental Price: $<%= @rental.price %></h3>
<% end %> 

<button><%= link_to "Edit Rental", edit_rental_path %></button>
<button><%= link_to "Show All Rentals", rentals_path %></button>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :age %><br>
<%= f.number_field :age %><br>

<h1>Or Create New Video Game</h1><br>

<%= f.fields_for :videogames do |game| %>
<%= game.label :title %><br>
<%= game.text_field :title %><br>
<%= game.label :erb_rating %><br>
<%= game.text_field :erb_rating %><br>

<% end %>

<br>
<%= f.submit "Create New User" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit this Rental</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |f| %>

<%= link_to f.name, user_path(f) %><br/>

<% end %>

app/views/users/new.html.erb
<h1>Create New User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>User Name: <%= @user.name %></h1>
<h2>User Age: <%= @user.age %></h2>

<ul>
<% @user.videogames.each do |game| %>
    <li><%= link_to game.title, videogame_path(game) %></li>
<% end %>
</ul>

<button><%=link_to "Edit This User", edit_user_path(@user) %></button>

app/views/videogames/_form.html.erb
<%= form_for @videogame do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :erb_rating %>
<%= f.text_field :erb_rating %>
<%= f.submit %>
<% end %>

app/views/videogames/edit.html.erb
<h1>Edit this Game</h1>

<%= render 'form' %>

app/views/videogames/index.html.erb
<h1>All Video Games</h1>

<ul>
<% @videogames.each do |videogame| %>
    <li><%= link_to videogame.title, videogame_path(videogame) %></li>
<% end %>
</ul>

<button><%= link_to "Create New VideoGame", new_videogame_path %></button>

app/views/videogames/new.html.erb
<h1>New Game Form</h1>

<%= render 'form' %>

app/views/videogames/show.html.erb
<h1>Game Title: <%= @videogame.title %></h1>
<h2>Game ERB Rating: <%= @videogame.erb_rating %></h2>

<button><%= link_to "Edit this Game", edit_videogame_path(@videogame) %></button>
<button><%= link_to "Return to All Games", videogames_path %></button>
<button><%= link_to "Delete This Game", videogame_path(@videogame), data: {:confirm => 'Are you sure?'}, :method => :delete %></button>